[logs]
log_level = "info"
log_format = "%(asctime)s - %(name)s[func: %(funcName)s line:%(lineno)d] - %(levelname)s: %(message)s"
log_console = true
log_path = '/var/log/logs/'
stacklevel = 2

[mysql]
host = "123.249.13.235"
port = 16030
db = "bookCity"
user = "bookCity"
passwd = "bookCity"
